### ISSUE TITLE
When installing via CPAN.pm, tests can't find _deflate under cpan in Perl 5.14.1 [rt.cpan.org #72786]

### ISSUE THREAD

**Issue by timbunce** [timbunce/devel-nytprof#54]
Migrated from [rt.cpan.org#72786](https://rt.cpan.org/Ticket/Display.html?id=72786) (status was 'open')

Requestors:
- bdfoy@cpan.org

From bdfoy@cpan.org on 2011-11-28 21:11:39:

```
When I tried to install 4.06 running cpan under 5.14.1 on Mac OS X.7.2, I got odd test failures. 
Building by hand I had no problem. This isn't a problem for me, but I'll just note that it 
happened in case someone else has the same problem.



$ cpan5.14.1 Devel::NYTProf
CPAN: File::HomeDir loaded ok (v0.98)
CPAN: Storable loaded ok (v2.27)
Going to read '/Users/brian/.cpan/Metadata'
  Database was generated on Sat, 19 Nov 2011 13:27:17 GMT
CPAN: LWP::UserAgent loaded ok (v6.02)
CPAN: URI::URL loaded ok (v5.03)
CPAN: YAML loaded ok (v0.77)
Going to read '/Volumes/Atlas/CPAN/authors/01mailrc.txt.gz'
CPAN: Compress::Zlib loaded ok (v2.033)
Going to read 127 yaml files from /Users/brian/.cpan/build/
...........................................................................DONE
Restored the state of none (in 1.9073 secs)
............................................................................DONE
Going to read '/Volumes/Atlas/CPAN/modules/02packages.details.txt.gz'
  Database was generated on Mon, 28 Nov 2011 13:29:31 GMT
...............
  New CPAN.pm version (v1.9800) available.
  [Currently running version is v1.9600]
  You might want to try
    install CPAN
    reload cpan
  to both upgrade CPAN.pm and run the new version without leaving
  the current session.


.............................................................DONE
Going to read '/Volumes/Atlas/CPAN/modules/03modlist.data.gz'
............................................................................DONE
Going to write /Users/brian/.cpan/Metadata
Running install for module 'Devel::NYTProf'
Running make for T/TI/TIMB/Devel-NYTProf-4.06.tar.gz
  Has already been unwrapped into directory /Users/brian/.cpan/build/Devel-NYTProf-4.06-
TKXkNF
CPAN: Parse::CPAN::Meta loaded ok (v1.4401)
CPAN: CPAN::Meta loaded ok (v2.110440)
CPAN: Module::CoreList loaded ok (v2.49_01)
  Has already been made
Running make test
cp blib/arch/auto/Devel/NYTProf/NYTProf.bundle 
blib/lib/Devel/auto/Devel/NYTProf/NYTProf.bundle
PERL_DL_NONLAZY=1 /usr/local/perls/perl-5.14.1/bin/perl "-MExtUtils::Command::MM" "-e" 
"test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
t/00-load.t ............ 1/2 
#   Failed test 'use Devel::NYTProf::Core;'
#   at t/00-load.t line 5.
#     Tried to use 'Devel::NYTProf::Core'.
#     Error:  Can't load '/Users/brian/.cpan/build/Devel-NYTProf-4.06-
TKXkNF/blib/lib/Devel/auto/Devel/NYTProf/NYTProf.bundle' for module Devel::NYTProf: 
dlopen(/Users/brian/.cpan/build/Devel-NYTProf-4.06-
TKXkNF/blib/lib/Devel/auto/Devel/NYTProf/NYTProf.bundle, 2): Symbol not found: _deflate
#   Referenced from: /Users/brian/.cpan/build/Devel-NYTProf-4.06-
TKXkNF/blib/lib/Devel/auto/Devel/NYTProf/NYTProf.bundle
#   Expected in: dynamic lookup
#  at /Users/brian/.cpan/build/Devel-NYTProf-4.06-TKXkNF/blib/lib/Devel/NYTProf/Core.pm 
line 19
# Compilation failed in require at (eval 4) line 2.
# BEGIN failed--compilation aborted at (eval 4) line 2.
# Testing Devel::NYTProf 4.06 started at Mon Nov 28 15:01:37 2011

#   Failed test 'use Devel::NYTProf::Constants;'
#   at t/00-load.t line 11.
#     Tried to use 'Devel::NYTProf::Constants'.
#     Error:  Attempt to reload Devel/NYTProf/Core.pm aborted.
# Compilation failed in require at /Users/brian/.cpan/build/Devel-NYTProf-4.06-
TKXkNF/blib/lib/Devel/NYTProf/Constants.pm line 5.
# BEGIN failed--compilation aborted at /Users/brian/.cpan/build/Devel-NYTProf-4.06-
TKXkNF/blib/lib/Devel/NYTProf/Constants.pm line 5.
# Compilation failed in require at (eval 5) line 2.
# BEGIN failed--compilation aborted at (eval 5) line 2.
Undefined subroutine &main::NYTP_DEFAULT_COMPRESSION called at t/00-load.t line 15.
# Looks like you failed 2 tests of 2.
# Looks like your test exited with 255 just after 2.
t/00-load.t ............ Dubious, test returned 255 (wstat 65280, 0xff00)
```

From timb@cpan.org on 2012-01-02 20:58:59:

```
I'm sorry for the long delay in replying. Is this still a problem?
```

From bdfoy@cpan.org on 2012-01-02 23:43:32:

```
On Mon Jan 02 15:58:59 2012, TIMB wrote:
> I'm sorry for the long delay in replying. Is this still a problem?

With Perl 5.14.2 and Devel::NYTProf 4.06, it's still a problem. I think this is an odd interaction 
with CPAN.pm. I don't see the problem when I compile by hand or use cpanp. 
```

**Comment by jkeenan** [comment]
> Migrated from [rt.cpan.org#72786](https://rt.cpan.org/Ticket/Display.html?id=72786) (status was 'open')
> 
> Requestors:
> 
>     * [bdfoy@cpan.org](mailto:bdfoy@cpan.org)
> 
> 
> From [bdfoy@cpan.org](mailto:bdfoy@cpan.org) on 2011-11-28 21:11:39:
> 
> ```
> When I tried to install 4.06 running cpan under 5.14.1 on Mac OS X.7.2, I got odd test failures. 
> Building by hand I had no problem. This isn't a problem for me, but I'll just note that it 
> happened in case someone else has the same problem.
> 
> 
> 
> $ cpan5.14.1 Devel::NYTProf
> CPAN: File::HomeDir loaded ok (v0.98)
> CPAN: Storable loaded ok (v2.27)
> Going to read '/Users/brian/.cpan/Metadata'
>   Database was generated on Sat, 19 Nov 2011 13:27:17 GMT
> CPAN: LWP::UserAgent loaded ok (v6.02)
> CPAN: URI::URL loaded ok (v5.03)
> CPAN: YAML loaded ok (v0.77)
> Going to read '/Volumes/Atlas/CPAN/authors/01mailrc.txt.gz'
> CPAN: Compress::Zlib loaded ok (v2.033)
> Going to read 127 yaml files from /Users/brian/.cpan/build/
> ...........................................................................DONE
> Restored the state of none (in 1.9073 secs)
> ............................................................................DONE
> Going to read '/Volumes/Atlas/CPAN/modules/02packages.details.txt.gz'
>   Database was generated on Mon, 28 Nov 2011 13:29:31 GMT
> ...............
>   New CPAN.pm version (v1.9800) available.
>   [Currently running version is v1.9600]
>   You might want to try
>     install CPAN
>     reload cpan
>   to both upgrade CPAN.pm and run the new version without leaving
>   the current session.
> 
> 
> .............................................................DONE
> Going to read '/Volumes/Atlas/CPAN/modules/03modlist.data.gz'
> ............................................................................DONE
> Going to write /Users/brian/.cpan/Metadata
> Running install for module 'Devel::NYTProf'
> Running make for T/TI/TIMB/Devel-NYTProf-4.06.tar.gz
>   Has already been unwrapped into directory /Users/brian/.cpan/build/Devel-NYTProf-4.06-
> TKXkNF
> CPAN: Parse::CPAN::Meta loaded ok (v1.4401)
> CPAN: CPAN::Meta loaded ok (v2.110440)
> CPAN: Module::CoreList loaded ok (v2.49_01)
>   Has already been made
> Running make test
> cp blib/arch/auto/Devel/NYTProf/NYTProf.bundle 
> blib/lib/Devel/auto/Devel/NYTProf/NYTProf.bundle
> PERL_DL_NONLAZY=1 /usr/local/perls/perl-5.14.1/bin/perl "-MExtUtils::Command::MM" "-e" 
> "test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
> t/00-load.t ............ 1/2 
> #   Failed test 'use Devel::NYTProf::Core;'
> #   at t/00-load.t line 5.
> #     Tried to use 'Devel::NYTProf::Core'.
> #     Error:  Can't load '/Users/brian/.cpan/build/Devel-NYTProf-4.06-
> TKXkNF/blib/lib/Devel/auto/Devel/NYTProf/NYTProf.bundle' for module Devel::NYTProf: 
> dlopen(/Users/brian/.cpan/build/Devel-NYTProf-4.06-
> TKXkNF/blib/lib/Devel/auto/Devel/NYTProf/NYTProf.bundle, 2): Symbol not found: _deflate
> #   Referenced from: /Users/brian/.cpan/build/Devel-NYTProf-4.06-
> TKXkNF/blib/lib/Devel/auto/Devel/NYTProf/NYTProf.bundle
> #   Expected in: dynamic lookup
> #  at /Users/brian/.cpan/build/Devel-NYTProf-4.06-TKXkNF/blib/lib/Devel/NYTProf/Core.pm 
> line 19
> # Compilation failed in require at (eval 4) line 2.
> # BEGIN failed--compilation aborted at (eval 4) line 2.
> # Testing Devel::NYTProf 4.06 started at Mon Nov 28 15:01:37 2011
> 
> #   Failed test 'use Devel::NYTProf::Constants;'
> #   at t/00-load.t line 11.
> #     Tried to use 'Devel::NYTProf::Constants'.
> #     Error:  Attempt to reload Devel/NYTProf/Core.pm aborted.
> # Compilation failed in require at /Users/brian/.cpan/build/Devel-NYTProf-4.06-
> TKXkNF/blib/lib/Devel/NYTProf/Constants.pm line 5.
> # BEGIN failed--compilation aborted at /Users/brian/.cpan/build/Devel-NYTProf-4.06-
> TKXkNF/blib/lib/Devel/NYTProf/Constants.pm line 5.
> # Compilation failed in require at (eval 5) line 2.
> # BEGIN failed--compilation aborted at (eval 5) line 2.
> Undefined subroutine &main::NYTP_DEFAULT_COMPRESSION called at t/00-load.t line 15.
> # Looks like you failed 2 tests of 2.
> # Looks like your test exited with 255 just after 2.
> t/00-load.t ............ Dubious, test returned 255 (wstat 65280, 0xff00)
> ```
> 

[snip]

> 
> From [bdfoy@cpan.org](mailto:bdfoy@cpan.org) on 2012-01-02 23:43:32:
> 
> ```

[snip]

> 
> With Perl 5.14.2 and Devel::NYTProf 4.06, it's still a problem. I think this is an odd interaction 
> with CPAN.pm. I don't see the problem when I compile by hand or use cpanp. 
> ```

@bdfoy, a new version (6.07) of Devel-NYTProf was released to CPAN this morning.  Can you let us know if this installation problem still appears?  (Extra credit for generating a CPANtesters report!)

Thank you very much.
Jim Keenan

**Comment by jkeenan** [comment]
Re-posting with better github ID for OP:  @briandfoy 

> > Migrated from [rt.cpan.org#72786](https://rt.cpan.org/Ticket/Display.html?id=72786) (status was 'open')
> > Requestors:
> > ```
> > * [bdfoy@cpan.org](mailto:bdfoy@cpan.org)
> > ```
> > 
> > 
> > From [bdfoy@cpan.org](mailto:bdfoy@cpan.org) on 2011-11-28 21:11:39:
> > ```
> > When I tried to install 4.06 running cpan under 5.14.1 on Mac OS X.7.2, I got odd test failures. 
> > Building by hand I had no problem. This isn't a problem for me, but I'll just note that it 
> > happened in case someone else has the same problem.
> > 
> > 
> > 
> > $ cpan5.14.1 Devel::NYTProf
> > CPAN: File::HomeDir loaded ok (v0.98)
> > CPAN: Storable loaded ok (v2.27)
> > Going to read '/Users/brian/.cpan/Metadata'
> >   Database was generated on Sat, 19 Nov 2011 13:27:17 GMT
> > CPAN: LWP::UserAgent loaded ok (v6.02)
> > CPAN: URI::URL loaded ok (v5.03)
> > CPAN: YAML loaded ok (v0.77)
> > Going to read '/Volumes/Atlas/CPAN/authors/01mailrc.txt.gz'
> > CPAN: Compress::Zlib loaded ok (v2.033)
> > Going to read 127 yaml files from /Users/brian/.cpan/build/
> > ...........................................................................DONE
> > Restored the state of none (in 1.9073 secs)
> > ............................................................................DONE
> > Going to read '/Volumes/Atlas/CPAN/modules/02packages.details.txt.gz'
> >   Database was generated on Mon, 28 Nov 2011 13:29:31 GMT
> > ...............
> >   New CPAN.pm version (v1.9800) available.
> >   [Currently running version is v1.9600]
> >   You might want to try
> >     install CPAN
> >     reload cpan
> >   to both upgrade CPAN.pm and run the new version without leaving
> >   the current session.
> > 
> > 
> > .............................................................DONE
> > Going to read '/Volumes/Atlas/CPAN/modules/03modlist.data.gz'
> > ............................................................................DONE
> > Going to write /Users/brian/.cpan/Metadata
> > Running install for module 'Devel::NYTProf'
> > Running make for T/TI/TIMB/Devel-NYTProf-4.06.tar.gz
> >   Has already been unwrapped into directory /Users/brian/.cpan/build/Devel-NYTProf-4.06-
> > TKXkNF
> > CPAN: Parse::CPAN::Meta loaded ok (v1.4401)
> > CPAN: CPAN::Meta loaded ok (v2.110440)
> > CPAN: Module::CoreList loaded ok (v2.49_01)
> >   Has already been made
> > Running make test
> > cp blib/arch/auto/Devel/NYTProf/NYTProf.bundle 
> > blib/lib/Devel/auto/Devel/NYTProf/NYTProf.bundle
> > PERL_DL_NONLAZY=1 /usr/local/perls/perl-5.14.1/bin/perl "-MExtUtils::Command::MM" "-e" 
> > "test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
> > t/00-load.t ............ 1/2 
> > #   Failed test 'use Devel::NYTProf::Core;'
> > #   at t/00-load.t line 5.
> > #     Tried to use 'Devel::NYTProf::Core'.
> > #     Error:  Can't load '/Users/brian/.cpan/build/Devel-NYTProf-4.06-
> > TKXkNF/blib/lib/Devel/auto/Devel/NYTProf/NYTProf.bundle' for module Devel::NYTProf: 
> > dlopen(/Users/brian/.cpan/build/Devel-NYTProf-4.06-
> > TKXkNF/blib/lib/Devel/auto/Devel/NYTProf/NYTProf.bundle, 2): Symbol not found: _deflate
> > #   Referenced from: /Users/brian/.cpan/build/Devel-NYTProf-4.06-
> > TKXkNF/blib/lib/Devel/auto/Devel/NYTProf/NYTProf.bundle
> > #   Expected in: dynamic lookup
> > #  at /Users/brian/.cpan/build/Devel-NYTProf-4.06-TKXkNF/blib/lib/Devel/NYTProf/Core.pm 
> > line 19
> > # Compilation failed in require at (eval 4) line 2.
> > # BEGIN failed--compilation aborted at (eval 4) line 2.
> > # Testing Devel::NYTProf 4.06 started at Mon Nov 28 15:01:37 2011
> > 
> > #   Failed test 'use Devel::NYTProf::Constants;'
> > #   at t/00-load.t line 11.
> > #     Tried to use 'Devel::NYTProf::Constants'.
> > #     Error:  Attempt to reload Devel/NYTProf/Core.pm aborted.
> > # Compilation failed in require at /Users/brian/.cpan/build/Devel-NYTProf-4.06-
> > TKXkNF/blib/lib/Devel/NYTProf/Constants.pm line 5.
> > # BEGIN failed--compilation aborted at /Users/brian/.cpan/build/Devel-NYTProf-4.06-
> > TKXkNF/blib/lib/Devel/NYTProf/Constants.pm line 5.
> > # Compilation failed in require at (eval 5) line 2.
> > # BEGIN failed--compilation aborted at (eval 5) line 2.
> > Undefined subroutine &main::NYTP_DEFAULT_COMPRESSION called at t/00-load.t line 15.
> > # Looks like you failed 2 tests of 2.
> > # Looks like your test exited with 255 just after 2.
> > t/00-load.t ............ Dubious, test returned 255 (wstat 65280, 0xff00)
> > ```
> 
> [snip]
> 
> > From [bdfoy@cpan.org](mailto:bdfoy@cpan.org) on 2012-01-02 23:43:32:
> 
> [snip]
> 
> > With Perl 5.14.2 and Devel::NYTProf 4.06, it's still a problem. I think this is an odd interaction
> > with CPAN.pm. I don't see the problem when I compile by hand or use cpanp.
> 
> @bdfoy, a new version (6.07) of Devel-NYTProf was released to CPAN this morning. Can you let us know if this installation problem still appears? (Extra credit for generating a CPANtesters report!)
> 
> Thank you very much.
> Jim Keenan

**Comment by briandfoy** [comment]
This works on macOS 10.15.3 with perls 5.14.4 and 5.32.1. Thanks,

**Comment by jkeenan** [comment]
> This works on macOS 10.15.3 with perls 5.14.4 and 5.32.1. Thanks,

Thanks.  Closing ticket.
